[tool.poetry]
name = "tep"
version = "0.2.3"
description = "A RESTful API testing framework inspired by JMeter's design."
license = "Apache-2.0"
readme = "README.md"
authors = ["dongfanger <2802358564@qq.com>"]

homepage = "https://github.com/dongfanger/tep"
repository = "https://github.com/dongfanger/tep"

keywords = ["RESTful", "API", "testing", "JMeter"]

classifiers = [
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8"
]

[tool.poetry.dependencies]
python = "^3.8"
pymysql = "^0.10.0"
faker = "^4.1.1"
jmespath = "^0.10.0"
openpyxl = "^3.0.4"
xlrd = "^1.2.0"
urllib3 = "^1.25.9"
pytest-ordering = "^0.6"
texttable = "^1.6.2"
SQLAlchemy = "^1.3.18"
requests = "^2.24.0"
allure-pytest = "^2.8.16"
allure-python-commons = "^2.8.16"
numpy = "^1.19.1"
pandas = "^1.0.5"
loguru = "^0.5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
wget = "^3.2"

[[tool.poetry.source]]
name = "tsinghua"
default = true
url = "https://pypi.tuna.tsinghua.edu.cn/simple"

[tool.poetry.scripts]
tep = "tep.cli:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

